In [108]:
import numpy as np

np.iinfo(np.int8)

iinfo(min=-128, max=127, dtype=int8)

In [109]:
np.iinfo(np.int16)

iinfo(min=-32768, max=32767, dtype=int16)

In [110]:
np.iinfo(np.int32)

iinfo(min=-2147483648, max=2147483647, dtype=int32)

In [111]:
np.iinfo(np.int64)

iinfo(min=-9223372036854775808, max=9223372036854775807, dtype=int64)

In [112]:
a = 25
b = np.int8(25)
type(a), type(b)

(int, numpy.int8)

In [113]:
a, b

(25, 25)

In [114]:
c = np.uint8(25)
print(c)
print(type(c))
np.iinfo(c)

25
<class 'numpy.uint8'>


iinfo(min=0, max=255, dtype=uint8)

In [115]:
print(len(np.sctypeDict))
print(*sorted(map(str, set(np.sctypeDict.values()))), sep='\n')

131
<class 'numpy.bool_'>
<class 'numpy.bytes_'>
<class 'numpy.clongdouble'>
<class 'numpy.complex128'>
<class 'numpy.complex64'>
<class 'numpy.datetime64'>
<class 'numpy.float16'>
<class 'numpy.float32'>
<class 'numpy.float64'>
<class 'numpy.int16'>
<class 'numpy.int32'>
<class 'numpy.int64'>
<class 'numpy.int8'>
<class 'numpy.intc'>
<class 'numpy.longdouble'>
<class 'numpy.object_'>
<class 'numpy.str_'>
<class 'numpy.timedelta64'>
<class 'numpy.uint16'>
<class 'numpy.uint32'>
<class 'numpy.uint64'>
<class 'numpy.uint8'>
<class 'numpy.uintc'>
<class 'numpy.void'>


In [116]:
a = True
print(type(a))

a = np.bool(a)
print(type(a))

a = np.bool_(a)
print(type(a))

<class 'bool'>
<class 'bool'>
<class 'numpy.bool_'>


C:\Users\79265\AppData\Local\Temp\ipykernel_3404\2086546266.py:4: DeprecationWarning: `np.bool` is a deprecated alias for the builtin `bool`. To silence this warning, use `bool` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.bool_` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  a = np.bool(a)


In [117]:
print(np.bool(True) == np.bool_(True))

print(type(np.bool(True)) == type(np.bool_(True)))

True
False


C:\Users\79265\AppData\Local\Temp\ipykernel_3404\2880610284.py:1: DeprecationWarning: `np.bool` is a deprecated alias for the builtin `bool`. To silence this warning, use `bool` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.bool_` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  print(np.bool(True) == np.bool_(True))
C:\Users\79265\AppData\Local\Temp\ipykernel_3404\2880610284.py:3: DeprecationWarning: `np.bool` is a deprecated alias for the builtin `bool`. To silence this warning, use `bool` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.bool_` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  print(type(np.bool(True)) == type(np.bool_(True)))


In [118]:
lst = [1,5,2,9,10]
arr = np.array(lst, dtype=np.int8)
arr
# array([ 1,  5,  2,  9, 10])

array([ 1,  5,  2,  9, 10], dtype=int8)

In [119]:
print(type(arr))

<class 'numpy.ndarray'>


In [120]:
arr.dtype

dtype('int8')

In [121]:
arr[2] = 2000
arr

array([  1,   5, -48,   9,  10], dtype=int8)

In [122]:
arr[2] = 125.5
arr

array([  1,   5, 125,   9,  10], dtype=int8)

In [123]:
arr[2] = '12'
arr

array([ 1,  5, 12,  9, 10], dtype=int8)

In [124]:
arr = np.float64(arr)
arr

array([ 1.,  5., 12.,  9., 10.])

In [125]:
np.finfo(np.float16)
# finfo(resolution=0.001, min=-6.55040e+04, max=6.55040e+04, dtype=float16)
np.finfo(np.float32)
# finfo(resolution=1e-06, min=-3.4028235e+38, max=3.4028235e+38, dtype=float32)
np.finfo(np.float64)
# finfo(resolution=1e-15, min=-1.7976931348623157e+308, max=1.7976931348623157e+308, dtype=float64)
#np.finfo(np.float128)
# finfo(resolution=1e-18, min=-1.189731495357231765e+4932, max=1.189731495357231765e+4932, dtype=float128)

finfo(resolution=1e-15, min=-1.7976931348623157e+308, max=1.7976931348623157e+308, dtype=float64)

In [126]:
arr = np.array([1,5,2,9,10], dtype=np.int8)
nd_arr = np.array([
               [12, 45, 78],
               [34, 56, 13],
               [12, 98, 76]
               ], dtype=np.int16)

In [127]:
arr.ndim

1

In [128]:
nd_arr.ndim

2

In [129]:
arr.size

5

In [130]:
nd_arr.size

9

In [131]:
arr.shape

(5,)

In [132]:
nd_arr.shape

(3, 3)

In [133]:
zeros_1d = np.zeros(5)
zeros_1d

array([0., 0., 0., 0., 0.])

In [134]:
zeros_3d = np.zeros((5,4,3), dtype=np.float32)
print(zeros_3d.shape)

(5, 4, 3)


In [135]:
arr = np.arange(8)
arr

array([0, 1, 2, 3, 4, 5, 6, 7])

In [136]:
arr.shape = (2, 4)
arr

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [137]:
arr = np.arange(8)
arr_new = arr.reshape((2, 4))
arr_new

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [138]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7])

In [139]:
arr_new = arr.reshape((2, 4), order='F')
arr_new

array([[0, 2, 4, 6],
       [1, 3, 5, 7]])

In [140]:
arr.shape = (2, 4)
arr

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [141]:
arr_trans = arr.transpose()
arr_trans

array([[0, 4],
       [1, 5],
       [2, 6],
       [3, 7]])

In [142]:
arr = np.linspace(1, 2, 6)
arr

array([1. , 1.2, 1.4, 1.6, 1.8, 2. ])

In [143]:
arr[2]

1.4

In [144]:
arr[2:4]

array([1.4, 1.6])

In [145]:
arr[::-1]

array([2. , 1.8, 1.6, 1.4, 1.2, 1. ])

In [146]:
nd_array =  np.linspace(0, 6, 12, endpoint=False).reshape(3,4)
nd_array

array([[0. , 0.5, 1. , 1.5],
       [2. , 2.5, 3. , 3.5],
       [4. , 4.5, 5. , 5.5]])

In [147]:
nd_array[1, 2] # до зпт - строка, после - столбец

3.0

In [148]:
nd_array[:2, 2]

array([1., 3.])

In [149]:
nd_array[1:, 2:4] # начиная с 2 строки (нумерация питон), 3-4 столбец (нумерация питон)

array([[3. , 3.5],
       [5. , 5.5]])

In [150]:
nd_array[:, 2:4] # все строки, 3-4 столбец (нумерация питон)

array([[1. , 1.5],
       [3. , 3.5],
       [5. , 5.5]])

In [151]:
nd_array[:2] #все столбцы (нет 2го :), 0-1 строки (нумерация питон)

array([[0. , 0.5, 1. , 1.5],
       [2. , 2.5, 3. , 3.5]])

In [152]:
data = np.array([4, 9, -4, 3])
roots = np.sqrt(data)
roots

C:\Users\79265\AppData\Local\Temp\ipykernel_3404\3612371969.py:2: RuntimeWarning: invalid value encountered in sqrt
  roots = np.sqrt(data)


array([2.        , 3.        ,        nan, 1.73205081])

In [153]:
sum(roots)

nan

In [154]:
np.isnan(roots)

array([False, False,  True, False])

In [155]:
roots[np.isnan(roots)]

array([nan])

In [156]:
roots[np.isnan(roots)] = 0
roots

array([2.        , 3.        , 0.        , 1.73205081])

In [159]:
data = np.array([4, 9, -4, 3, -36, -9])
roots = np.sqrt(data)
roots

C:\Users\79265\AppData\Local\Temp\ipykernel_3404\166047963.py:2: RuntimeWarning: invalid value encountered in sqrt
  roots = np.sqrt(data)


array([2.        , 3.        ,        nan, 1.73205081,        nan,
              nan])

In [160]:
roots[np.isnan(roots)] = 0
roots

array([2.        , 3.        , 0.        , 1.73205081, 0.        ,
       0.        ])

In [161]:
sum(roots)

6.732050807568877

In [162]:
vec1 = np.array([2, 4, 7, 2.5])
vec2 = np.array([12, 6, 3.6, 13])
vec1 + vec2

array([14. , 10. , 10.6, 15.5])

In [163]:
list1 = [2, 4, 7, 2.5]
list2 = [12, 6, 3.6, 13]
list1 + list2

[2, 4, 7, 2.5, 12, 6, 3.6, 13]

In [164]:
[x + y for x, y in zip(list1, list2)]

[14, 10, 10.6, 15.5]

In [166]:
vec1 * vec2

array([24. , 24. , 25.2, 32.5])

In [167]:
vec1 > vec2

array([False, False,  True, False])

In [168]:
vec = np.array([14,15,9,26,53,5,89])
vec <= 26

array([ True,  True,  True,  True, False,  True, False])

In [172]:
vec = np.array([3, 4])
length = np.sqrt(np.sum(vec ** 2))
length

5.0

In [173]:
length = np.linalg.norm(vec)
length

5.0

In [174]:
vec1 = np.array([0, 3, 5])
vec2 = np.array([12, 4, 7])
distance = np.sqrt(np.sum((vec1 - vec2) ** 2))
distance

12.206555615733702

In [175]:
distance = np.linalg.norm(vec1 - vec2)
distance

12.206555615733702

In [176]:
vec1 = np.arange(1, 6)
vec2 = np.linspace(10, 20, 5)
scalar_product = np.sum(vec1 * vec2)
scalar_product

250.0

In [177]:
print(vec1, vec2, sep='\n')

[1 2 3 4 5]
[10.  12.5 15.  17.5 20. ]


In [180]:
scalar_product = np.dot(vec1, vec2)
scalar_product

250.0

In [181]:
x = np.array([25, 0])
y = np.array([0, 10])
np.dot(x, y)

0

In [183]:
np.random.rand()

0.5718513894528677

In [184]:
np.random.rand() * 100

4.60864382291537

In [185]:
np.random.rand(5)

array([0.48985447, 0.36448797, 0.97617606, 0.43374256, 0.70408372])

In [186]:
np.random.rand(2, 3)

array([[0.45500221, 0.90648311, 0.46567961],
       [0.25160251, 0.02343384, 0.15004083]])

In [187]:
shape = (2, 3)
np.random.sample(shape)

array([[0.840799  , 0.16580171, 0.22034086],
       [0.65530777, 0.88380866, 0.49595071]])

In [188]:
np.random.uniform(-30, 50)

28.58783228876939

In [189]:
np.random.uniform(0.5, 0.75, size=5)

array([0.5571238 , 0.615381  , 0.68501574, 0.7266002 , 0.57382878])

In [190]:
np.random.uniform(-1000, 500, size=(2, 3))

array([[ 398.17480197, -271.57932055, -656.29045385],
       [-776.16832731,   31.29799003,  455.91442265]])

In [191]:
np.random.randint(4, size=(2,3))

array([[1, 2, 3],
       [3, 0, 2]])

In [193]:
np.random.randint(6, 12, size=(3,3))

array([[10, 11,  7],
       [ 9,  6,  8],
       [ 9,  6,  7]])

In [195]:
arr = np.arange(6)
print(arr)
print(np.random.shuffle(arr))
print(arr)

[0 1 2 3 4 5]
None
[2 3 4 5 1 0]


In [197]:
playlist = ["The Beatles", "Pink Floyd", "ACDC", "Deep Purple"]
shuffled = np.random.permutation(playlist)
print(playlist)
print(shuffled)
print(playlist)


['The Beatles', 'Pink Floyd', 'ACDC', 'Deep Purple']
['Pink Floyd' 'The Beatles' 'ACDC' 'Deep Purple']
['The Beatles', 'Pink Floyd', 'ACDC', 'Deep Purple']


In [199]:
print(type(playlist), type(shuffled), sep='\n')

<class 'list'>
<class 'numpy.ndarray'>


In [200]:
np.random.permutation(10)

array([4, 0, 7, 3, 2, 9, 5, 6, 1, 8])

In [201]:
workers = ['Ivan', 'Nikita', 'Maria', 'John', 'Kate']
 
choice = np.random.choice(workers, size=2, replace=False)
print(choice)

['Nikita' 'Kate']


In [202]:
choice = np.random.choice([1,2,3,4,5,6], size=10)
print(choice)

[6 2 2 5 6 1 4 2 5 2]


In [203]:
np.random.seed(23)
np.random.randint(10, size=(3,4))
# array([[3, 6, 8, 9],
#        [6, 8, 7, 9],
#        [3, 6, 1, 2]])

array([[3, 6, 8, 9],
       [6, 8, 7, 9],
       [3, 6, 1, 2]])

In [207]:
np.random.seed(100)
print(np.random.randint(10, size=3))
# [8 8 3]
print(np.random.randint(10, size=3))
# [7 7 0]
print(np.random.randint(10, size=3))
# [4 2 5]

[8 8 3]
[7 7 0]
[4 2 5]


In [216]:
num = "-65536"
a = np.int16(num)
a

0

In [217]:
elem = np.nan
np.isnan(elem)

True

In [218]:
elem is np.nan 

True

In [219]:
a = 2147483548
b = 2147471336

a + b

4294954884

In [220]:
np.iinfo(a)

iinfo(min=-2147483648, max=2147483647, dtype=int32)

In [222]:
2**32

4294967296

In [224]:
np.iinfo(np.int64)

iinfo(min=-9223372036854775808, max=9223372036854775807, dtype=int64)

In [232]:
# Напишите функцию get_chess, которая принимает на вход длину стороны квадрата a и возвращает двумерный массив формы (a, a), 
# заполненный 0 и 1 в шахматном порядке. В левом верхнем углу всегда должен быть ноль.

def get_chess(a):
    array = np.zeros((a, a)) # создаем массив,заолненный 0
    array[1::2, ::2] = 1 # начиная со 1й строки (нумерация питон) (1) и до конца т-цы (::), каждая 2я строка (::2). каждый 2й столбец (, ::2), начиная с 0го (нумерация питон). выводит четные элементы нечетных строк (нумерация питон)
    array[::2, 1::2] = 1 # начиная с 0 строки (нумерация питон) (ничего до первого :) и до концва т-цы (::), каждая 2я строка (::2). каж 2й столбец, начиная с 1го (нумерация питон) (1::2). выводит нечет эл-ты чет строк (нум. питон)
    return array


get_chess(4)

array([[0., 1., 0., 1.],
       [1., 0., 1., 0.],
       [0., 1., 0., 1.],
       [1., 0., 1., 0.]])

In [229]:
# Вы разрабатываете приложение для прослушивания музыки. Конечно же, там будет доступна функция перемешивания плейлиста. 
# Пользователю может настолько понравиться перемешанная версия плейлиста, что он захочет сохранить его копию. 
# Однако вы не хотите хранить в памяти новую версию плейлиста, а просто хотите сохранять тот seed, с которым он был сгенерирован.
# Для этого напишите функцию shuffle_seed(<array>),  которая принимает на вход массив из чисел, генерирует случайное число для seed 
# в диапазоне от 0 до 2**32 - 1 (включительно) и возвращает кортеж: перемешанный с данным seed массив 
# (исходный массив должен оставаться без изменений), а также seed, с которым этот массив был получен.

def shuffle_seed(array):
    seed = np.random.randint(2 ** 31)
    np.random.seed(seed)
    
    shuffled = np.random.permutation(array)
    return shuffled, seed

array = [1, 2, 3, 4, 5]
shuffle_seed(array)
shuffle_seed(array)

(array([2, 4, 3, 1, 5]), 16018015)

In [233]:
# Напишите функцию min_max_dist, которая принимает на вход неограниченное число векторов через запятую. 
# Гарантируется, что все векторы, которые передаются, одинаковой длины.
# Функция возвращает минимальное и максимальное расстояние между векторами в виде кортежа.

def min_max_dist(*vectors):
    dist = []
    for i in range(len(vectors)):
        for j in range(i+1, len(vectors)):
            distance = np.linalg.norm(vectors[i] - vectors[j])
            dist.append(distance)
    
    return min(dist), max(dist)

vec1 = np.array([1,2,3])
vec2 = np.array([4,5,6])
vec3 = np.array([7, 8, 9])
 
min_max_dist(vec1, vec2, vec3)

(5.196152422706632, 10.392304845413264)

In [236]:
#Напишите функцию any_normal, которая принимает на вход неограниченное число векторов через запятую. 
# Гарантируется, что все векторы, которые передаются, одинаковой длины.
# Функция возвращает True, если есть хотя бы одна пара перпендикулярных векторов. Иначе возвращает False.

def any_normal(*vectors):
    for i in range(len(vectors)):
        for j in range(i+1, len(vectors)):
            if np.dot(vectors[i], vectors[j]) == 0:
                return True
    return False
    
vec1 = np.array([2, 1])
vec2 = np.array([-1, 2])
vec3 = np.array([3,4])

any_normal(vec1, vec2, vec3)

True

In [238]:
#Напишите функцию get_loto(num), генерирующую трёхмерный массив случайных целых чисел от 1 до 100 (включительно). Это поля для игры в лото.
# Трёхмерный массив должен состоять из таблиц чисел формы 5х5, то есть итоговая форма — (num, 5, 5).
# Функция возвращает полученный массив.

def get_loto(num):
    array = np.random.randint(1, 101, size=(num, 5, 5))
    return array
    
get_loto(2)

array([[[ 1,  5, 83, 42, 42],
        [10, 46, 23, 93,  7],
        [70, 82, 89, 21, 45],
        [90,  1, 10, 87, 67],
        [15, 60, 23, 52, 56]],

       [[90, 35, 24, 69,  5],
        [ 9, 59,  2, 34, 32],
        [24, 61, 17, 29, 45],
        [64, 44, 28, 92,  3],
        [27, 88,  8, 35, 28]]])

In [241]:
#Напишите функцию get_unique_loto(num). Она генерирует num полей для игры в лото, однако на каждом поле 5х5 числа не могут повторяться. 
# Функция также должна возвращать массив формы num x 5 x 5.

def get_unique_loto(num):
    a = np.arange(1, 101)
    lst = []
    for i in range(num):
        lst.append(np.random.choice(a, size=(5,5), replace=False))
    
    arr = np.array(lst)
    return arr

get_unique_loto(2)

array([[[98, 45, 14, 66, 56],
        [53, 49, 24, 41, 36],
        [16, 85, 52, 72, 69],
        [10, 67, 13, 95,  7],
        [23, 99, 76, 51, 96]],

       [[38, 79, 51, 17, 86],
        [35, 99, 15, 16, 47],
        [69,  2, 60, 48, 78],
        [52, 29,  7, 89, 45],
        [32, 27, 74, 61, 13]]])